server:
  port: 8080

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:~/local
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  type-aliases-package: com.flab.infrun
  configuration:
    map-underscore-to-camel-case: true