server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://infrun-database:3306/infrun
        username: ${SPRING_DATASOURCE_USER}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
        hibernate:
            ddl-auto: update

jwt:
    secret: ${JWT_SECRET}
    access-token-expiry-secs: ${JWT_TOKEN_VALIDITY_IN_SECONDS}
    issuer: 'infrun'
