server:
  port: 8080

spring:
  application:
    name: infrun
  profiles:
    active: local

logging.level:
  org.hibernate.SQL: debug

aws:
  s3:
    bucketName: infrun
    profileName: InfrunManager
    region: ap-northeast-2
    duration: 30
